### ISSUE TITLE
Хеш пароля в таблице пользователей

### ISSUE THREAD

**Issue by solodyagin** [donpadlo/webuseorg3#1]
Реализовать хранение и проверку пароля по хешу в таблице пользователей. Предлагаю использовать sha1 + salt

**Comment by zerogle** [comment]
6c24aca7101a6cba3b90b9c8000cd87a799bfc53

**Comment by zerogle** [comment]
удалить из таблицы users столбец pass

**Comment by solodyagin** [comment]
fixed b08c645cc5a0965a1329e5a39853b3cf3a3e2d27
