### ISSUE TITLE
Не удаляются записи из справочников

### ISSUE THREAD

**Issue by skive** [donpadlo/webuseorg3#20]
Актуальная клонированная версия из github.
Никакие записи из справочников не удаляются.

**Comment by donpadlo** [comment]
И не будут. Реализована 1С подобная система удаления. Т.е. вы помечаете на удаление. А физически удалять - пункт меню в настройках

**Comment by skive** [comment]
Пункт меню в настройках отрабатывает.
Но записи, тем не менее, не удаляются.

**Comment by donpadlo** [comment]
Значит какието зависимости есть. Потому не дает удалить. На скайп постучитесь, пообщаемся. pvtuning
