### ISSUE TITLE
Table 'users_quick_menu' doesn't exist

### ISSUE THREAD

**Issue by skive** [donpadlo/webuseorg3#21]
Актуальная клонированная с github версия.
В шапке сайта выводиться ошибка:
	Неверный запрос выборки закладок: Table 'office.**users_quick_menu**' doesn't exist

**Comment by donpadlo** [comment]
выполните скрипт update.php

**Comment by donpadlo** [comment]
поправил webuser.sql

**Comment by skive** [comment]
Проблема решена, спасибо.
