### ISSUE TITLE
Кодировка

### ISSUE THREAD

**Issue by Glavnyuk** [donpadlo/webuseorg3#7]
При создании базы с кодировокой utf8_general_ci 
при входе часть текста в виде 
Ð£Ñ‡ÐµÑ‚ Ð¢ÐœÐ¦ Ð² Ð¾Ñ€Ð³Ð°Ð½Ð¸Ð·Ð°Ñ†Ð¸Ð
Подскажите где ошибся.

**Comment by donpadlo** [comment]
Устанавливали при помощи инсталлятора или руками базу заливали? Какая ОС ?

**Comment by Glavnyuk** [comment]
ubuntu server 14.04
устанваливал инсталятором: создал пустую базу, запустил инсталятор, переименовал конфиг, зашел на index.php.

**Comment by Glavnyuk** [comment]
Apache/2.4.7 (Ubuntu)
Версия клиента базы данных: libmysql - 5.5.46

**Comment by donpadlo** [comment]
В файле config.php попробуйте указать $codemysql = 'utf8-bin';   или $codemysql = 'utf8_general_ci';

**Comment by Glavnyuk** [comment]
Спасибо!
